// Default empty deal form values
export const EMPTY_DEAL = {
  bu:'', sales_type:'External', stage:'Pipeline',
  client:'', region:'Europe', country:'',
  sales_owner:'', description:'',
  go_live_month: '', go_live_year: '',
  invoice_date: '',
  // Contract period — required for every business model
  contract_start: '', contract_end: '',
  // Multi-year deferral schedule (financed_project) — { FY26: 936200, … }
  revenue_by_fy: null,
  value_total:'', gm_pct:'',
  rec_month:'', rec_year:'',
  cs_day:1, cs_month:'', cs_year:'', ce_day:31, ce_month:'', ce_year:'',
  lost_reason:'',
  win_probability:'',
  currency: 'EUR',
  exchange_rate: '',
  end_customer: '',
  distributor: '',
  hub: '',
  end_customer_value: '',
  // Structured distribution network
  distribution_path:  '',
  distributor_id:     null,
  hub_id:             null,
  vgt_cost:           '',
  distributor_price:  '',
  end_customer_price: '',
  company_id: '',
  list_price: '',
  discount_requested: '',
  discount_note_dist: '',
  product: '',
  business_model: '',
  warranty_months: 36,
  equipment_count: '',
  annual_studies: '',
  annual_exams: '',
}
